name: Lakehouse CI/CD - Main Branch

on:
  push:
    branches:
      - main

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    name: Validate and Deploy Step Function

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install AWS CLI (with --update)
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate Python Syntax
        run: |
          python -m py_compile \
            glue_jobs/product_etl.py \
            glue_jobs/orders_etl.py \
            glue_jobs/order_items_etl.py \
            glue_jobs/archive_and_mark_processed.py

      - name: Deploy Step Function Definition
        run: |
          aws stepfunctions update-state-machine \
            --state-machine-arn arn:aws:states:eu-west-1:371439860588:stateMachine:EcommerceLakehouseOrchestration \
            --definition file://step_functions/lakehouse_etl_stepfunction.json
