name: Lakehouse CI - Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  validate-scripts:
    runs-on: ubuntu-latest
    name: Lint Python Scripts

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install linter
        run: pip install flake8

      - name: Run flake8 linting
        run: flake8 product_etl.py orders_etl.py order_items_etl.py archive_and_mark_processed.py
